### ISSUE TITLE
How to dump DexFile?

### ISSUE THREAD

**Issue by brandonros** [thouger/android_study#1]
```rust
#[derive(Debug)]
struct MemoryMapping {
    start_addr: String,
    end_addr: String,
    permissions: String,
    offset: String,
    device: String,
    inode: String,
    path: String,
}

pub fn get_libart_base() -> Option<u32> {
    let contents = std::fs::read_to_string("/proc/self/maps").unwrap();
    let re = regex::Regex::new(r"([0-9a-f]+)-([0-9a-f]+) (\S+) (\S+) (\S+) (\S+) (.+)").unwrap();
    let mappings: Vec<MemoryMapping> = contents
        .lines()
        .filter_map(|line| {
            re.captures(line).map(|captures| MemoryMapping {
                start_addr: captures.get(1).unwrap().as_str().trim().to_string(),
                end_addr: captures.get(2).unwrap().as_str().trim().to_string(),
                permissions: captures.get(3).unwrap().as_str().trim().to_string(),
                offset: captures.get(4).unwrap().as_str().trim().to_string(),
                device: captures.get(5).unwrap().as_str().trim().to_string(),
                inode: captures.get(6).unwrap().as_str().trim().to_string(),
                path: captures.get(7).unwrap().as_str().trim().to_string(),
            })
        })
        .collect();
    let libart_mapping = mappings.iter().find(|mapping| mapping.path == "/apex/com.android.art/lib/libart.so");
    if libart_mapping.is_none() {
        return None;
    }
    let libart_mapping = libart_mapping.unwrap();
    let libart_start = u32::from_str_radix(&libart_mapping.start_addr, 16).unwrap();
    return Some(libart_start);
}

pub static LIBART_DEFINECLASS: Lazy<DefineClass_fn> = Lazy::new(|| {
    let libart_base = jni_helpers::get_libart_base().unwrap();
    let ghidra_base = 0x00010000;
    let flat_address = 0x003390f4 - ghidra_base;
    let mapped_address = (libart_base + flat_address + 1) as *const c_void; // TODO: + 1 due to thumb vs arm
    return unsafe { std::mem::transmute::<*const c_void, DefineClass_fn>(mapped_address) };
});

pub extern "C" fn DefineClasss_hook(
    class_linker_this: *const c_void, 
    thread_self: *const c_void,
    descriptor: *const c_char,
    hash: size_t,
    handle_class_loader: *const c_void,
    dex_file: *const c_void,
    dex_class_def: *const c_void
) -> *const c_void {
    // TODO: preserve stack/registers/state?
    let descriptor_string = utilities::convert_c_string_to_rust_string(descriptor);
    log::info!("DefineClasss_hook class_linker_this = {class_linker_this:p} thread_self = {thread_self:p} descriptor = {descriptor:p} descriptor_string = {descriptor_string} hash = {hash:x} handle_class_loader = {handle_class_loader:p} dex_file = {dex_file:p} dex_class_def = {dex_class_def:p}");
    let guard = DEFINECLASS_HOOK_STRUCT.lock().unwrap();
    let hook_struct = guard.as_ref().unwrap();
    let ori_fn_address = hook_struct.ori_fn_address;
    let ori_fn_bytes = hook_struct.ori_fn_bytes.clone();
    let patch_fn_bytes = hook_struct.patch_fn_bytes.clone();
    assert_eq!(ori_fn_bytes.len(), patch_fn_bytes.len());
    drop(guard);
    // Restore the original bytes.
    disable_hook(ori_fn_address, &ori_fn_bytes);
    // Call original.
    let ret_val = unsafe { LIBART_DEFINECLASS(class_linker_this, thread_self, descriptor, hash, handle_class_loader, dex_file, dex_class_def) };
    // Patch again to point to your hook.
    enable_hook(ori_fn_address, &patch_fn_bytes);
    log::info!("DefineClasss_hook class_linker_this = {class_linker_this:p} thread_self = {thread_self:p} descriptor = {descriptor:p} descriptor_string = {descriptor_string} hash = {hash:x} handle_class_loader = {handle_class_loader:p} dex_file = {dex_file:p} dex_class_def = {dex_class_def:p} ret_val = {ret_val:p}");
    // TODO: restore stack/registers/state?
    return ret_val;
}
```

I ran into your codebase by searching `_ZN3art11ClassLinker11DefineClassEPNS_6ThreadEPKcjNS_6HandleINS_6mirror11ClassLoaderEEERKNS_7DexFileERKNS_3dex8ClassDefE`

As you can see, I have similar, but in Rust.

I am able to see (as part of obfuscation/protection) classes being `DefineClass`'d at runtime. How do we dump the `DexFile` bytes from memory?

**Comment by thouger** [comment]
I rarely try to dump dex from memory. Before dex is loaded, it usually exists as a file, so its location can be found through `BaseDexClassLoader`, like this.

> public BaseDexClassLoader(String dexPath, File optimizedDirectory,
  String librarySearchPath, ClassLoader parent, boolean isTrusted) {
  this(dexPath, librarySearchPath, parent, null, null, isTrusted);
  }

`dexPath` is the dex path. I usually use this script [here](https://github.com/thouger/frida_script/blob/main/src/java/findClass.js). If it is more complicated, you need to use an art dump, like this [one](https://github.com/Youlor/Youpk).

**Comment by brandonros** [comment]
```
08-14 11:58:22.092 21994 21994 I libHook: common::libart_hooks: DefineClasss_hook class_linker_this = 0xe8cc2780 thread_self = 0xe8d04c00 descriptor = 0xe7641a60 descriptor_string = Lcom/redacted/redacted/main/redacted/redacted; hash = 4a964d0e handle_class_loader = 0xffa9eb2c dex_file = 0xe7db8e60 dex_class_def = 0xb5076634 ret_val = 0x13b0afd0
```

If `dex_file` is `const DexFile& dex_file,` and `DexFile` has https://android.googlesource.com/platform/dalvik2/+/refs/heads/master/dx/src/com/android/dx/dex/file/DexFile.java#213 ` public byte[] toDex(Writer humanOut, boolean verbose)`, how to invoke `toDex`? Need to do C++ base table?

Otherwise, as to what you said, how to hook from `libart.so` `BaseDexClassLoader` constructor?

**Comment by thouger** [comment]
I rarely see people using `toDex `at runtime, as far as I know, DexFile is used more in repackaging like this:https://github.com/virjarRatel/ratel-core/blob/392dc1f13ba6152ee684954d8d1d9bef278c12e9/base-lib-dx/src/main/java/external/com/android/dx/dex/file/DexFile.java
`DexFile`  Usually used like this `public DexFile(String fileName)` or `public DexFile(File file)`，it will not be used in art runtime

> Otherwise, as to what you said, how to hook from libart.so BaseDexClassLoader constructor?

frida is a suitable tool，I usually use https://github.com/thouger/frida_script/blob/main/src/java/findClass.ts
`BaseDexClassLoader `It is a method that can hook to dynamically load dex

**Comment by brandonros** [comment]
Frida is very invasive and some Java applications have good packed obfuscated native library running multiple threads + forks to make sure no debugger like Frida attaching/pausing threads/injecting (hiding syscalls, invalid ELF, etc.)

I will report if I get it. I think I see what to do. Thanks for `BaseDexClassLoader` recommendation. I will try `com.highcapable.yukihookapi.hook.entity.YukiBaseHooker` on `dalvik.system.BaseDexClassLoader` constructor.

**Comment by thouger** [comment]
There are some examples of modifying frida's fingerprint https://github.com/Ylarod/Florida, can bypass most apps and some large app like tiktok,taobao,pdd and jd,If frida and app are in the same process, use frida-gumjs, it will be more difficult to be detected

**Comment by brandonros** [comment]
```kotlin
findClass("dalvik.system.BaseDexClassLoader").hook {
   injectMember {
       constructor {
           param(
               String::class.java,
               File::class.java,
               String::class.java,
               ClassLoader::class.java
           )
       }
       beforeHook {
           loggerD(msg = "${Redacted.TAG}: BaseDexClassLoader constructor")
       }
   }
}

findClass("dalvik.system.DexFile").hook {
   injectMember {
       constructor {
           param(
               String::class.java
           )
       }
       beforeHook {
           loggerD(msg = "${Redacted.TAG}: DexFile constructor ${args(0).any()}")
       }
   }
}

findClass("dalvik.system.DexFile").hook {
   injectMember {
       constructor {
           param(
               File::class.java
           )
       }
       beforeHook {
           loggerD(msg = "${Redacted.TAG}: DexFile constructor ${args(0).any()}")
       }
   }
}

```

None of these are being called, I see mentions of `OatDexFile`

Do we think `DexFile` is old from Dalvik and `OatDexFile` is new for AndroidRuntime or no I am wrong?

Edit: DexFile was deprecated in API Level 26 https://developer.android.com/reference/dalvik/system/DexFile
